/**
 * Drizzle schema (spec §7). Storage ONLY — no business logic here.
 *
 * Conventions:
 * - UUID (v4, text) primary keys everywhere — multi-user + cloud-ready.
 *   IDs are generated by repositories (src/lib/uuid.ts), never by SQLite,
 *   so this file stays importable by drizzle-kit under plain Node.
 * - Money columns are INTEGER minor units in the row's native `currency`
 *   (fils/cents/yen). Scale lives in domain/money.ts, never "×100".
 * - `date` columns are ISO `YYYY-MM-DD` strings; `*_at` columns are ISO
 *   datetime strings (UTC).
 */
import { index, integer, real, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core';

export const ASSET_CLASSES = ['EQUITY', 'CRYPTO', 'ETF', 'PROPERTY', 'COLLECTIBLE'] as const;
export type AssetClass = (typeof ASSET_CLASSES)[number];

export const TRANSACTION_TYPES = [
  'BUY',
  'SELL',
  'DIVIDEND',
  'RENT',
  'FEE',
  'MAINTENANCE',
  'TRANSFER',
  'VALUATION_MARK',
] as const;
export type TransactionType = (typeof TRANSACTION_TYPES)[number];

export const CHANGE_SOURCES = ['voice', 'manual', 'import', 'system'] as const;
export type ChangeSource = (typeof CHANGE_SOURCES)[number];

export const assets = sqliteTable(
  'assets',
  {
    id: text('id').primaryKey(),
    class: text('class', { enum: ASSET_CLASSES }).notNull(),
    name: text('name').notNull(),
    /** Platform/location holding the asset (eToro, IBKR, Reeman, home safe…). */
    platform: text('platform'),
    /** Native currency of the asset's valuation. */
    currency: text('currency').notNull(),
    /** Ticker/symbol for auto-priced classes (AAPL, BTC…). */
    symbol: text('symbol'),
    /** Provider pricing id (spec §6): Stooq `aapl.us` / CoinGecko `bitcoin`.
     *  Null on a market-class asset = unpriced (flagged like a collectible). */
    providerId: text('provider_id'),
    /** Collectibles: grade + grader (PSA/BGS/CGC); null elsewhere. */
    grade: text('grade'),
    grader: text('grader'),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (t) => [index('assets_class_idx').on(t.class), index('assets_platform_idx').on(t.platform)]
);

/*
 * NOTE: there is deliberately NO stored `lots` table (spec §6 v3). Cost-basis
 * lots are DERIVED from BUY/SELL transactions — a single source of truth —
 * so a re-imported statement that dedups a transaction can never leave a
 * duplicated lot double-counting cost basis. Convention: BUY/SELL
 * `amount_minor` is quantity × unit price only; fees are separate FEE rows.
 */
export const transactions = sqliteTable(
  'transactions',
  {
    id: text('id').primaryKey(),
    assetId: text('asset_id')
      .notNull()
      .references(() => assets.id),
    type: text('type', { enum: TRANSACTION_TYPES }).notNull(),
    date: text('date').notNull(),
    /** Signed cashflow in minor units of `currency`: buys/fees −, sells/income +. */
    amountMinor: integer('amount_minor').notNull(),
    currency: text('currency').notNull(),
    quantity: real('quantity'),
    /** One-off labor on this transaction (spec §4); flows into the return engine. */
    hoursSpent: real('hours_spent').notNull().default(0),
    /** Account/platform the row came from — part of the dedup fingerprint. */
    sourceAccount: text('source_account'),
    /** Broker/order transaction ID from the statement, when provided — the
     *  only reliable idempotency key (spec §6 v3). */
    sourceTxnId: text('source_txn_id'),
    /** imports.id that produced this row (null = manual/voice). */
    sourceRef: text('source_ref'),
    /** Dedup key: hash(asset+account+source_txn_id) when the broker gave us
     *  an ID, else hash(asset+date+type+quantity+amount+account). */
    fingerprint: text('fingerprint').notNull(),
    note: text('note'),
    createdAt: text('created_at').notNull(),
  },
  (t) => [
    uniqueIndex('transactions_fingerprint_uq').on(t.fingerprint),
    index('transactions_asset_date_idx').on(t.assetId, t.date),
  ]
);

export const valuationMarks = sqliteTable(
  'valuation_marks',
  {
    id: text('id').primaryKey(),
    assetId: text('asset_id')
      .notNull()
      .references(() => assets.id),
    date: text('date').notNull(),
    valueMinor: integer('value_minor').notNull(),
    currency: text('currency').notNull(),
    source: text('source', { enum: CHANGE_SOURCES }).notNull(),
    note: text('note'),
    createdAt: text('created_at').notNull(),
  },
  (t) => [index('valuation_marks_asset_date_idx').on(t.assetId, t.date)]
);

export const imports = sqliteTable('imports', {
  id: text('id').primaryKey(),
  fileName: text('file_name').notNull(),
  kind: text('kind', { enum: ['pdf', 'csv', 'screenshot', 'voice'] }).notNull(),
  /** Broker/platform the statement came from (eToro…). */
  platform: text('platform'),
  /** Account whose activity this statement covers — coverage windows are
   *  matched per-account during dedup (spec §6). */
  sourceAccount: text('source_account'),
  /** Statement coverage window — powers gap/overlap detection (spec §6). */
  periodStart: text('period_start'),
  periodEnd: text('period_end'),
  status: text('status', { enum: ['pending', 'processed', 'failed'] })
    .notNull()
    .default('pending'),
  importedAt: text('imported_at').notNull(),
});

export const settings = sqliteTable(
  'settings',
  {
    id: text('id').primaryKey(),
    /** e.g. 'hourly_rate_minor', 'hourly_rate_currency', 'base_currency'. */
    key: text('key').notNull(),
    value: text('value').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (t) => [uniqueIndex('settings_key_uq').on(t.key)]
);

export const fxRates = sqliteTable(
  'fx_rates',
  {
    id: text('id').primaryKey(),
    /** 1 unit of `base` = `rate` units of `quote`. Rates are not money — real is fine. */
    base: text('base').notNull(),
    quote: text('quote').notNull(),
    rate: real('rate').notNull(),
    asOf: text('as_of').notNull(),
  },
  (t) => [uniqueIndex('fx_rates_pair_asof_uq').on(t.base, t.quote, t.asOf)]
);

export const priceCache = sqliteTable(
  'price_cache',
  {
    id: text('id').primaryKey(),
    symbol: text('symbol').notNull(),
    currency: text('currency').notNull(),
    priceMinor: integer('price_minor').notNull(),
    asOf: text('as_of').notNull(),
  },
  (t) => [uniqueIndex('price_cache_symbol_uq').on(t.symbol, t.currency)]
);

/**
 * Persisted symbol-mapping cache (spec §6, 7B-2): normalized name/ticker
 * key → confirmed binding. Written when an asset binds (index pick or a
 * gate-passed AI proposal); read by the shared resolver so the same name
 * never needs re-resolution — and never splits into two assets.
 */
export const symbolMappings = sqliteTable(
  'symbol_mappings',
  {
    id: text('id').primaryKey(),
    /** Normalized lookup key (norm(): trim + uppercase). */
    key: text('key').notNull(),
    class: text('class', { enum: ['EQUITY', 'CRYPTO', 'ETF'] }).notNull(),
    displayName: text('display_name').notNull(),
    symbol: text('symbol').notNull(),
    providerId: text('provider_id').notNull(),
    currency: text('currency').notNull(),
    source: text('source', { enum: ['index', 'ai', 'manual'] }).notNull(),
    createdAt: text('created_at').notNull(),
  },
  (t) => [uniqueIndex('symbol_mappings_key_class_uq').on(t.key, t.class)]
);

/**
 * Dedup review queue (spec §6): weak-key collisions and near-matches park
 * here for one-tap keep / merge / discard — never silently dropped, never
 * an uncaught DB throw. `payload` is the parsed-transaction JSON.
 */
export const reviewItems = sqliteTable(
  'review_items',
  {
    id: text('id').primaryKey(),
    importId: text('import_id')
      .notNull()
      .references(() => imports.id),
    /** Resolved asset the incoming row points at. */
    assetId: text('asset_id')
      .notNull()
      .references(() => assets.id),
    /** JSON of the incoming ParsedTransaction awaiting a decision. */
    payload: text('payload').notNull(),
    reason: text('reason', {
      enum: ['weak-collision', 'near-match', 'binding-confirm'],
    }).notNull(),
    /** transactions.id of the existing row it collided/near-matched with. */
    conflictsWith: text('conflicts_with'),
    status: text('status', { enum: ['pending', 'kept', 'merged', 'discarded'] })
      .notNull()
      .default('pending'),
    createdAt: text('created_at').notNull(),
    resolvedAt: text('resolved_at'),
  },
  (t) => [index('review_items_status_idx').on(t.status)]
);

/** Audit trail (spec §7): every manually-set number writes a row here. */
export const changeLog = sqliteTable(
  'change_log',
  {
    id: text('id').primaryKey(),
    /** Table name of the changed entity ('assets', 'transactions', 'settings'…). */
    entity: text('entity').notNull(),
    entityId: text('entity_id').notNull(),
    field: text('field').notNull(),
    oldValue: text('old_value'),
    newValue: text('new_value'),
    source: text('source', { enum: CHANGE_SOURCES }).notNull(),
    timestamp: text('timestamp').notNull(),
  },
  (t) => [index('change_log_entity_idx').on(t.entity, t.entityId)]
);
