/**
 * Bundled US equities + major ETFs snapshot (offline typeahead, spec §6).
 * providerId is the Stooq id: lowercase ticker + `.us` — format verified
 * live 2026-07 against stooq.com/q/l (e.g. `aapl.us`, `msft.us`).
 * Curated large-caps + majors; extend as holdings appear. Class B / dotted
 * tickers use Stooq's dash form (BRK-B → brk-b.us).
 */
import type { SecurityEntry } from './types';

const eq = (displayName: string, symbol: string, exchange: string): SecurityEntry => ({
  displayName,
  symbol,
  class: 'EQUITY',
  exchange,
  providerId: `${symbol.toLowerCase().replace(/\./g, '-')}.us`,
  currency: 'USD',
});

const etf = (displayName: string, symbol: string, exchange: string): SecurityEntry => ({
  ...eq(displayName, symbol, exchange),
  class: 'ETF',
});

export const US_EQUITIES: SecurityEntry[] = [
  eq('Apple Inc.', 'AAPL', 'NASDAQ'),
  eq('Microsoft Corporation', 'MSFT', 'NASDAQ'),
  eq('Alphabet Inc. Class A', 'GOOGL', 'NASDAQ'),
  eq('Alphabet Inc. Class C', 'GOOG', 'NASDAQ'),
  eq('Amazon.com Inc.', 'AMZN', 'NASDAQ'),
  eq('NVIDIA Corporation', 'NVDA', 'NASDAQ'),
  eq('Meta Platforms Inc.', 'META', 'NASDAQ'),
  eq('Tesla Inc.', 'TSLA', 'NASDAQ'),
  eq('Berkshire Hathaway Class B', 'BRK.B', 'NYSE'),
  eq('JPMorgan Chase & Co.', 'JPM', 'NYSE'),
  eq('Visa Inc.', 'V', 'NYSE'),
  eq('Mastercard Incorporated', 'MA', 'NYSE'),
  eq('Johnson & Johnson', 'JNJ', 'NYSE'),
  eq('Walmart Inc.', 'WMT', 'NYSE'),
  eq('Procter & Gamble Company', 'PG', 'NYSE'),
  eq('The Home Depot Inc.', 'HD', 'NYSE'),
  eq('Exxon Mobil Corporation', 'XOM', 'NYSE'),
  eq('Chevron Corporation', 'CVX', 'NYSE'),
  eq('The Coca-Cola Company', 'KO', 'NYSE'),
  eq('PepsiCo Inc.', 'PEP', 'NASDAQ'),
  eq('Costco Wholesale Corporation', 'COST', 'NASDAQ'),
  eq('Adobe Inc.', 'ADBE', 'NASDAQ'),
  eq('Salesforce Inc.', 'CRM', 'NYSE'),
  eq('Netflix Inc.', 'NFLX', 'NASDAQ'),
  eq('Advanced Micro Devices Inc.', 'AMD', 'NASDAQ'),
  eq('Intel Corporation', 'INTC', 'NASDAQ'),
  eq('Oracle Corporation', 'ORCL', 'NYSE'),
  eq('Cisco Systems Inc.', 'CSCO', 'NASDAQ'),
  eq('Broadcom Inc.', 'AVGO', 'NASDAQ'),
  eq('QUALCOMM Incorporated', 'QCOM', 'NASDAQ'),
  eq('Texas Instruments Incorporated', 'TXN', 'NASDAQ'),
  eq('Micron Technology Inc.', 'MU', 'NASDAQ'),
  eq('Applied Materials Inc.', 'AMAT', 'NASDAQ'),
  eq('Marvell Technology Inc.', 'MRVL', 'NASDAQ'),
  eq('Analog Devices Inc.', 'ADI', 'NASDAQ'),
  eq('Lam Research Corporation', 'LRCX', 'NASDAQ'),
  eq('KLA Corporation', 'KLAC', 'NASDAQ'),
  eq('Arm Holdings plc ADR', 'ARM', 'NASDAQ'),
  eq('Super Micro Computer Inc.', 'SMCI', 'NASDAQ'),
  eq('International Business Machines', 'IBM', 'NYSE'),
  eq('UnitedHealth Group Incorporated', 'UNH', 'NYSE'),
  eq('Eli Lilly and Company', 'LLY', 'NYSE'),
  eq('Merck & Co. Inc.', 'MRK', 'NYSE'),
  eq('Pfizer Inc.', 'PFE', 'NYSE'),
  eq('AbbVie Inc.', 'ABBV', 'NYSE'),
  eq('Bristol-Myers Squibb Company', 'BMY', 'NYSE'),
  eq('Amgen Inc.', 'AMGN', 'NASDAQ'),
  eq('Gilead Sciences Inc.', 'GILD', 'NASDAQ'),
  eq('Thermo Fisher Scientific Inc.', 'TMO', 'NYSE'),
  eq('Abbott Laboratories', 'ABT', 'NYSE'),
  eq('Danaher Corporation', 'DHR', 'NYSE'),
  eq('Intuitive Surgical Inc.', 'ISRG', 'NASDAQ'),
  eq('Bank of America Corporation', 'BAC', 'NYSE'),
  eq('Wells Fargo & Company', 'WFC', 'NYSE'),
  eq('The Goldman Sachs Group Inc.', 'GS', 'NYSE'),
  eq('Morgan Stanley', 'MS', 'NYSE'),
  eq('Citigroup Inc.', 'C', 'NYSE'),
  eq('American Express Company', 'AXP', 'NYSE'),
  eq('BlackRock Inc.', 'BLK', 'NYSE'),
  eq('The Charles Schwab Corporation', 'SCHW', 'NYSE'),
  eq('S&P Global Inc.', 'SPGI', 'NYSE'),
  eq("Moody's Corporation", 'MCO', 'NYSE'),
  eq('The Walt Disney Company', 'DIS', 'NYSE'),
  eq('NIKE Inc.', 'NKE', 'NYSE'),
  eq("McDonald's Corporation", 'MCD', 'NYSE'),
  eq('Starbucks Corporation', 'SBUX', 'NASDAQ'),
  eq('AT&T Inc.', 'T', 'NYSE'),
  eq('Verizon Communications Inc.', 'VZ', 'NYSE'),
  eq('T-Mobile US Inc.', 'TMUS', 'NASDAQ'),
  eq('General Electric Company', 'GE', 'NYSE'),
  eq('Caterpillar Inc.', 'CAT', 'NYSE'),
  eq('The Boeing Company', 'BA', 'NYSE'),
  eq('3M Company', 'MMM', 'NYSE'),
  eq('Honeywell International Inc.', 'HON', 'NASDAQ'),
  eq('United Parcel Service Inc.', 'UPS', 'NYSE'),
  eq('FedEx Corporation', 'FDX', 'NYSE'),
  eq('RTX Corporation', 'RTX', 'NYSE'),
  eq('Lockheed Martin Corporation', 'LMT', 'NYSE'),
  eq('Deere & Company', 'DE', 'NYSE'),
  eq('PayPal Holdings Inc.', 'PYPL', 'NASDAQ'),
  eq('Shopify Inc.', 'SHOP', 'NYSE'),
  eq('Uber Technologies Inc.', 'UBER', 'NYSE'),
  eq('Airbnb Inc.', 'ABNB', 'NASDAQ'),
  eq('Coinbase Global Inc.', 'COIN', 'NASDAQ'),
  eq('Palantir Technologies Inc.', 'PLTR', 'NASDAQ'),
  eq('Snowflake Inc.', 'SNOW', 'NYSE'),
  eq('Spotify Technology S.A.', 'SPOT', 'NYSE'),
  eq('Palo Alto Networks Inc.', 'PANW', 'NASDAQ'),
  eq('ServiceNow Inc.', 'NOW', 'NYSE'),
  eq('Intuit Inc.', 'INTU', 'NASDAQ'),
  eq('Booking Holdings Inc.', 'BKNG', 'NASDAQ'),
  eq('Marriott International Inc.', 'MAR', 'NASDAQ'),
  eq('Linde plc', 'LIN', 'NASDAQ'),
  eq('NextEra Energy Inc.', 'NEE', 'NYSE'),
  eq("Lowe's Companies Inc.", 'LOW', 'NYSE'),
  eq('Target Corporation', 'TGT', 'NYSE'),
  eq('The TJX Companies Inc.', 'TJX', 'NYSE'),
  eq('General Motors Company', 'GM', 'NYSE'),
  eq('Ford Motor Company', 'F', 'NYSE'),
  eq('Rivian Automotive Inc.', 'RIVN', 'NASDAQ'),
  eq('Taiwan Semiconductor ADR', 'TSM', 'NYSE'),
  eq('ASML Holding N.V. ADR', 'ASML', 'NASDAQ'),
  eq('Alibaba Group Holding ADR', 'BABA', 'NYSE'),
  eq('JD.com Inc. ADR', 'JD', 'NASDAQ'),
  eq('PDD Holdings Inc. ADR', 'PDD', 'NASDAQ'),
  eq('NIO Inc. ADR', 'NIO', 'NYSE'),
  eq('Sony Group Corporation ADR', 'SONY', 'NYSE'),
  eq('Toyota Motor Corporation ADR', 'TM', 'NYSE'),
  eq('Accenture plc', 'ACN', 'NYSE'),
  eq('Automatic Data Processing Inc.', 'ADP', 'NASDAQ'),
  eq('Autodesk Inc.', 'ADSK', 'NASDAQ'),
  eq('American Electric Power Company', 'AEP', 'NASDAQ'),
  eq('Aflac Incorporated', 'AFL', 'NYSE'),
  eq('American International Group', 'AIG', 'NYSE'),
  eq('The Allstate Corporation', 'ALL', 'NYSE'),
  eq('American Tower Corporation', 'AMT', 'NYSE'),
  eq('Arista Networks Inc.', 'ANET', 'NYSE'),
  eq('Aon plc', 'AON', 'NYSE'),
  eq('Air Products and Chemicals Inc.', 'APD', 'NYSE'),
  eq('Amphenol Corporation', 'APH', 'NYSE'),
  eq('Axon Enterprise Inc.', 'AXON', 'NASDAQ'),
  eq('AutoZone Inc.', 'AZO', 'NYSE'),
  eq('Becton Dickinson and Company', 'BDX', 'NYSE'),
  eq('Biogen Inc.', 'BIIB', 'NASDAQ'),
  eq('The Bank of New York Mellon', 'BK', 'NYSE'),
  eq('Baker Hughes Company', 'BKR', 'NASDAQ'),
  eq('Boston Scientific Corporation', 'BSX', 'NYSE'),
  eq('Blackstone Inc.', 'BX', 'NYSE'),
  eq('Chubb Limited', 'CB', 'NYSE'),
  eq('Crown Castle Inc.', 'CCI', 'NYSE'),
  eq('Cadence Design Systems Inc.', 'CDNS', 'NASDAQ'),
  eq('Constellation Energy Corporation', 'CEG', 'NASDAQ'),
  eq('The Cigna Group', 'CI', 'NYSE'),
  eq('Comcast Corporation', 'CMCSA', 'NASDAQ'),
  eq('CME Group Inc.', 'CME', 'NASDAQ'),
  eq('Chipotle Mexican Grill Inc.', 'CMG', 'NYSE'),
  eq('Centene Corporation', 'CNC', 'NYSE'),
  eq('Capital One Financial Corporation', 'COF', 'NYSE'),
  eq('ConocoPhillips', 'COP', 'NYSE'),
  eq('Copart Inc.', 'CPRT', 'NASDAQ'),
  eq('CrowdStrike Holdings Inc.', 'CRWD', 'NASDAQ'),
  eq('CSX Corporation', 'CSX', 'NASDAQ'),
  eq('Cintas Corporation', 'CTAS', 'NASDAQ'),
  eq('CVS Health Corporation', 'CVS', 'NYSE'),
  eq('Dominion Energy Inc.', 'D', 'NYSE'),
  eq('Delta Air Lines Inc.', 'DAL', 'NYSE'),
  eq('Datadog Inc.', 'DDOG', 'NASDAQ'),
  eq('Dell Technologies Inc.', 'DELL', 'NYSE'),
  eq('D.R. Horton Inc.', 'DHI', 'NYSE'),
  eq("Domino's Pizza Inc.", 'DPZ', 'NASDAQ'),
  eq('Dow Inc.', 'DOW', 'NYSE'),
  eq('DexCom Inc.', 'DXCM', 'NASDAQ'),
  eq('Electronic Arts Inc.', 'EA', 'NASDAQ'),
  eq('eBay Inc.', 'EBAY', 'NASDAQ'),
  eq('Ecolab Inc.', 'ECL', 'NYSE'),
  eq('The Estée Lauder Companies', 'EL', 'NYSE'),
  eq('Emerson Electric Co.', 'EMR', 'NYSE'),
  eq('EOG Resources Inc.', 'EOG', 'NYSE'),
  eq('Equinix Inc.', 'EQIX', 'NASDAQ'),
  eq('Eaton Corporation plc', 'ETN', 'NYSE'),
  eq('Edwards Lifesciences Corporation', 'EW', 'NYSE'),
  eq('Exelon Corporation', 'EXC', 'NASDAQ'),
  eq('Freeport-McMoRan Inc.', 'FCX', 'NYSE'),
  eq('Fortinet Inc.', 'FTNT', 'NASDAQ'),
  eq('General Dynamics Corporation', 'GD', 'NYSE'),
  eq('GE HealthCare Technologies', 'GEHC', 'NASDAQ'),
  eq('General Mills Inc.', 'GIS', 'NYSE'),
  eq('Corning Incorporated', 'GLW', 'NYSE'),
  eq('Halliburton Company', 'HAL', 'NYSE'),
  eq('HCA Healthcare Inc.', 'HCA', 'NYSE'),
  eq('Hilton Worldwide Holdings', 'HLT', 'NYSE'),
  eq('Robinhood Markets Inc.', 'HOOD', 'NASDAQ'),
  eq('HP Inc.', 'HPQ', 'NYSE'),
  eq('The Hershey Company', 'HSY', 'NYSE'),
  eq('Humana Inc.', 'HUM', 'NYSE'),
  eq('Intercontinental Exchange Inc.', 'ICE', 'NYSE'),
  eq('IDEXX Laboratories Inc.', 'IDXX', 'NASDAQ'),
  eq('Illumina Inc.', 'ILMN', 'NASDAQ'),
  eq('IQVIA Holdings Inc.', 'IQV', 'NYSE'),
  eq('Illinois Tool Works Inc.', 'ITW', 'NYSE'),
  eq('Johnson Controls International', 'JCI', 'NYSE'),
  eq('The Kraft Heinz Company', 'KHC', 'NASDAQ'),
  eq('KKR & Co. Inc.', 'KKR', 'NYSE'),
  eq('Kinder Morgan Inc.', 'KMI', 'NYSE'),
  eq('The Kroger Co.', 'KR', 'NYSE'),
  eq('Lennar Corporation', 'LEN', 'NYSE'),
  eq('Lululemon Athletica Inc.', 'LULU', 'NASDAQ'),
  eq('Las Vegas Sands Corp.', 'LVS', 'NYSE'),
  eq('Lyft Inc.', 'LYFT', 'NASDAQ'),
  eq('Microchip Technology Inc.', 'MCHP', 'NASDAQ'),
  eq('Medtronic plc', 'MDT', 'NYSE'),
  eq('MercadoLibre Inc.', 'MELI', 'NASDAQ'),
  eq('MetLife Inc.', 'MET', 'NYSE'),
  eq('Marsh & McLennan Companies', 'MMC', 'NYSE'),
  eq('Monster Beverage Corporation', 'MNST', 'NASDAQ'),
  eq('Altria Group Inc.', 'MO', 'NYSE'),
  eq('Marathon Petroleum Corporation', 'MPC', 'NYSE'),
  eq('Moderna Inc.', 'MRNA', 'NASDAQ'),
  eq('MSCI Inc.', 'MSCI', 'NYSE'),
  eq('Motorola Solutions Inc.', 'MSI', 'NYSE'),
  eq('Strategy Inc. (MicroStrategy)', 'MSTR', 'NASDAQ'),
  eq('Newmont Corporation', 'NEM', 'NYSE'),
  eq('Cloudflare Inc.', 'NET', 'NYSE'),
  eq('Northrop Grumman Corporation', 'NOC', 'NYSE'),
  eq('Norfolk Southern Corporation', 'NSC', 'NYSE'),
  eq('NXP Semiconductors N.V.', 'NXPI', 'NASDAQ'),
  eq('Realty Income Corporation', 'O', 'NYSE'),
  eq('ONEOK Inc.', 'OKE', 'NYSE'),
  eq('Okta Inc.', 'OKTA', 'NASDAQ'),
  eq('ON Semiconductor Corporation', 'ON', 'NASDAQ'),
  eq("O'Reilly Automotive Inc.", 'ORLY', 'NASDAQ'),
  eq('Occidental Petroleum Corporation', 'OXY', 'NYSE'),
  eq('Paychex Inc.', 'PAYX', 'NASDAQ'),
  eq('PACCAR Inc.', 'PCAR', 'NASDAQ'),
  eq('Public Service Enterprise Group', 'PEG', 'NYSE'),
  eq('The Progressive Corporation', 'PGR', 'NYSE'),
  eq('Parker-Hannifin Corporation', 'PH', 'NYSE'),
  eq('Prologis Inc.', 'PLD', 'NYSE'),
  eq('Philip Morris International', 'PM', 'NYSE'),
  eq('The PNC Financial Services Group', 'PNC', 'NYSE'),
  eq('Public Storage', 'PSA', 'NYSE'),
  eq('Phillips 66', 'PSX', 'NYSE'),
  eq('Regeneron Pharmaceuticals Inc.', 'REGN', 'NASDAQ'),
  eq('Roblox Corporation', 'RBLX', 'NYSE'),
  eq('Rockwell Automation Inc.', 'ROK', 'NYSE'),
  eq('Roper Technologies Inc.', 'ROP', 'NASDAQ'),
  eq('Ross Stores Inc.', 'ROST', 'NASDAQ'),
  eq('Republic Services Inc.', 'RSG', 'NYSE'),
  eq('The Sherwin-Williams Company', 'SHW', 'NYSE'),
  eq('SLB (Schlumberger)', 'SLB', 'NYSE'),
  eq('Snap Inc.', 'SNAP', 'NYSE'),
  eq('Synopsys Inc.', 'SNPS', 'NASDAQ'),
  eq('Simon Property Group Inc.', 'SPG', 'NYSE'),
  eq('Sempra', 'SRE', 'NYSE'),
  eq('Constellation Brands Inc.', 'STZ', 'NYSE'),
  eq('Stryker Corporation', 'SYK', 'NYSE'),
  eq('Sysco Corporation', 'SYY', 'NYSE'),
  eq('TransDigm Group Incorporated', 'TDG', 'NYSE'),
  eq('Atlassian Corporation', 'TEAM', 'NASDAQ'),
  eq('Truist Financial Corporation', 'TFC', 'NYSE'),
  eq('The Travelers Companies Inc.', 'TRV', 'NYSE'),
  eq('The Trade Desk Inc.', 'TTD', 'NASDAQ'),
  eq('Take-Two Interactive Software', 'TTWO', 'NASDAQ'),
  eq('Textron Inc.', 'TXT', 'NYSE'),
  eq('Unity Software Inc.', 'U', 'NYSE'),
  eq('United Airlines Holdings Inc.', 'UAL', 'NASDAQ'),
  eq('Union Pacific Corporation', 'UNP', 'NYSE'),
  eq('U.S. Bancorp', 'USB', 'NYSE'),
  eq('Valero Energy Corporation', 'VLO', 'NYSE'),
  eq('Vertex Pharmaceuticals Inc.', 'VRTX', 'NASDAQ'),
  eq('Workday Inc.', 'WDAY', 'NASDAQ'),
  eq('Waste Management Inc.', 'WM', 'NYSE'),
  eq('The Williams Companies Inc.', 'WMB', 'NYSE'),
  eq('Xylem Inc.', 'XYL', 'NYSE'),
  eq('Yum! Brands Inc.', 'YUM', 'NYSE'),
  eq('Zscaler Inc.', 'ZS', 'NASDAQ'),
  eq('Pinterest Inc.', 'PINS', 'NYSE'),
  eq('Block Inc.', 'XYZ', 'NYSE'),
  eq('DoorDash Inc.', 'DASH', 'NASDAQ'),
  eq('SoFi Technologies Inc.', 'SOFI', 'NASDAQ'),
  eq('Affirm Holdings Inc.', 'AFRM', 'NASDAQ'),
  eq('GameStop Corp.', 'GME', 'NYSE'),
  eq('Carvana Co.', 'CVNA', 'NYSE'),
  eq('Etsy Inc.', 'ETSY', 'NASDAQ'),
  eq('Roku Inc.', 'ROKU', 'NASDAQ'),
  eq('Twilio Inc.', 'TWLO', 'NYSE'),
  eq('DraftKings Inc.', 'DKNG', 'NASDAQ'),
  eq('Celsius Holdings Inc.', 'CELH', 'NASDAQ'),
];

export const US_ETFS: SecurityEntry[] = [
  etf('SPDR S&P 500 ETF Trust', 'SPY', 'NYSEARCA'),
  etf('Vanguard S&P 500 ETF', 'VOO', 'NYSEARCA'),
  etf('iShares Core S&P 500 ETF', 'IVV', 'NYSEARCA'),
  etf('Vanguard Total Stock Market ETF', 'VTI', 'NYSEARCA'),
  etf('Invesco QQQ Trust', 'QQQ', 'NASDAQ'),
  etf('SPDR Dow Jones Industrial Average ETF', 'DIA', 'NYSEARCA'),
  etf('iShares Russell 2000 ETF', 'IWM', 'NYSEARCA'),
  etf('Vanguard FTSE Developed Markets ETF', 'VEA', 'NYSEARCA'),
  etf('Vanguard FTSE Emerging Markets ETF', 'VWO', 'NYSEARCA'),
  etf('iShares MSCI EAFE ETF', 'EFA', 'NYSEARCA'),
  etf('iShares MSCI Emerging Markets ETF', 'EEM', 'NYSEARCA'),
  etf('iShares Core U.S. Aggregate Bond ETF', 'AGG', 'NYSEARCA'),
  etf('Vanguard Total Bond Market ETF', 'BND', 'NASDAQ'),
  etf('iShares 20+ Year Treasury Bond ETF', 'TLT', 'NASDAQ'),
  etf('iShares iBoxx $ Inv Grade Corporate Bond ETF', 'LQD', 'NYSEARCA'),
  etf('iShares iBoxx $ High Yield Corporate Bond ETF', 'HYG', 'NYSEARCA'),
  etf('SPDR Gold Shares', 'GLD', 'NYSEARCA'),
  etf('iShares Silver Trust', 'SLV', 'NYSEARCA'),
  etf('VanEck Gold Miners ETF', 'GDX', 'NYSEARCA'),
  etf('Technology Select Sector SPDR Fund', 'XLK', 'NYSEARCA'),
  etf('Financial Select Sector SPDR Fund', 'XLF', 'NYSEARCA'),
  etf('Energy Select Sector SPDR Fund', 'XLE', 'NYSEARCA'),
  etf('Health Care Select Sector SPDR Fund', 'XLV', 'NYSEARCA'),
  etf('Consumer Discretionary Select SPDR Fund', 'XLY', 'NYSEARCA'),
  etf('Consumer Staples Select Sector SPDR Fund', 'XLP', 'NYSEARCA'),
  etf('Industrial Select Sector SPDR Fund', 'XLI', 'NYSEARCA'),
  etf('Utilities Select Sector SPDR Fund', 'XLU', 'NYSEARCA'),
  etf('Vanguard Real Estate ETF', 'VNQ', 'NYSEARCA'),
  etf('Schwab U.S. Dividend Equity ETF', 'SCHD', 'NYSEARCA'),
  etf('Vanguard Dividend Appreciation ETF', 'VIG', 'NYSEARCA'),
  etf('Vanguard High Dividend Yield ETF', 'VYM', 'NYSEARCA'),
  etf('JPMorgan Equity Premium Income ETF', 'JEPI', 'NYSEARCA'),
  etf('ARK Innovation ETF', 'ARKK', 'NYSEARCA'),
  etf('VanEck Semiconductor ETF', 'SMH', 'NASDAQ'),
  etf('iShares Semiconductor ETF', 'SOXX', 'NASDAQ'),
  etf('iShares Bitcoin Trust ETF', 'IBIT', 'NASDAQ'),
  etf('Vanguard Growth ETF', 'VUG', 'NYSEARCA'),
  etf('Vanguard Value ETF', 'VTV', 'NYSEARCA'),
  etf('Vanguard Small-Cap ETF', 'VB', 'NYSEARCA'),
  etf('Vanguard Mid-Cap ETF', 'VO', 'NYSEARCA'),
  etf('Vanguard Total International Stock ETF', 'VXUS', 'NASDAQ'),
  etf('Vanguard Total International Bond ETF', 'BNDX', 'NASDAQ'),
  etf('iShares Core S&P Mid-Cap ETF', 'IJH', 'NYSEARCA'),
  etf('iShares Core S&P Small-Cap ETF', 'IJR', 'NYSEARCA'),
  etf('Invesco S&P 500 Equal Weight ETF', 'RSP', 'NYSEARCA'),
  etf('Communication Services Select SPDR Fund', 'XLC', 'NYSEARCA'),
  etf('iShares Core S&P Total US Stock Market ETF', 'ITOT', 'NYSEARCA'),
  etf('SPDR Portfolio S&P 500 ETF', 'SPLG', 'NYSEARCA'),
  etf('Invesco NASDAQ 100 ETF', 'QQQM', 'NASDAQ'),
  etf('Vanguard Information Technology ETF', 'VGT', 'NYSEARCA'),
  etf('iShares Core MSCI Emerging Markets ETF', 'IEMG', 'NYSEARCA'),
  etf('iShares Core MSCI EAFE ETF', 'IEFA', 'NYSEARCA'),
  etf('iShares TIPS Bond ETF', 'TIP', 'NYSEARCA'),
  etf('iShares 1-3 Year Treasury Bond ETF', 'SHY', 'NASDAQ'),
  etf('iShares 7-10 Year Treasury Bond ETF', 'IEF', 'NASDAQ'),
  etf('iShares MSCI USA Min Vol Factor ETF', 'USMV', 'NYSEARCA'),
  etf('iShares MSCI USA Momentum Factor ETF', 'MTUM', 'NYSEARCA'),
  etf('iShares Biotechnology ETF', 'IBB', 'NASDAQ'),
  etf('SPDR S&P Biotech ETF', 'XBI', 'NYSEARCA'),
  etf('SPDR S&P Regional Banking ETF', 'KRE', 'NYSEARCA'),
  etf('SPDR S&P Oil & Gas Exploration ETF', 'XOP', 'NYSEARCA'),
  etf('iShares Core Dividend Growth ETF', 'DGRO', 'NYSEARCA'),
  etf('Fidelity Wise Origin Bitcoin Fund', 'FBTC', 'NYSEARCA'),
  etf('iShares Ethereum Trust ETF', 'ETHA', 'NASDAQ'),
];
