/**
 * Bundled US equities + major ETFs snapshot (offline typeahead, spec §6).
 * providerId is the Stooq id: lowercase ticker + `.us` — format verified
 * live 2026-07 against stooq.com/q/l (e.g. `aapl.us`, `msft.us`).
 * Curated large-caps + majors; extend as holdings appear. Class B / dotted
 * tickers use Stooq's dash form (BRK-B → brk-b.us).
 */
import type { SecurityEntry } from './types';

const eq = (displayName: string, symbol: string, exchange: string): SecurityEntry => ({
  displayName,
  symbol,
  class: 'EQUITY',
  exchange,
  providerId: `${symbol.toLowerCase().replace(/\./g, '-')}.us`,
  currency: 'USD',
});

const etf = (displayName: string, symbol: string, exchange: string): SecurityEntry => ({
  ...eq(displayName, symbol, exchange),
  class: 'ETF',
});

export const US_EQUITIES: SecurityEntry[] = [
  eq('Apple Inc.', 'AAPL', 'NASDAQ'),
  eq('Microsoft Corporation', 'MSFT', 'NASDAQ'),
  eq('Alphabet Inc. Class A', 'GOOGL', 'NASDAQ'),
  eq('Alphabet Inc. Class C', 'GOOG', 'NASDAQ'),
  eq('Amazon.com Inc.', 'AMZN', 'NASDAQ'),
  eq('NVIDIA Corporation', 'NVDA', 'NASDAQ'),
  eq('Meta Platforms Inc.', 'META', 'NASDAQ'),
  eq('Tesla Inc.', 'TSLA', 'NASDAQ'),
  eq('Berkshire Hathaway Class B', 'BRK.B', 'NYSE'),
  eq('JPMorgan Chase & Co.', 'JPM', 'NYSE'),
  eq('Visa Inc.', 'V', 'NYSE'),
  eq('Mastercard Incorporated', 'MA', 'NYSE'),
  eq('Johnson & Johnson', 'JNJ', 'NYSE'),
  eq('Walmart Inc.', 'WMT', 'NYSE'),
  eq('Procter & Gamble Company', 'PG', 'NYSE'),
  eq('The Home Depot Inc.', 'HD', 'NYSE'),
  eq('Exxon Mobil Corporation', 'XOM', 'NYSE'),
  eq('Chevron Corporation', 'CVX', 'NYSE'),
  eq('The Coca-Cola Company', 'KO', 'NYSE'),
  eq('PepsiCo Inc.', 'PEP', 'NASDAQ'),
  eq('Costco Wholesale Corporation', 'COST', 'NASDAQ'),
  eq('Adobe Inc.', 'ADBE', 'NASDAQ'),
  eq('Salesforce Inc.', 'CRM', 'NYSE'),
  eq('Netflix Inc.', 'NFLX', 'NASDAQ'),
  eq('Advanced Micro Devices Inc.', 'AMD', 'NASDAQ'),
  eq('Intel Corporation', 'INTC', 'NASDAQ'),
  eq('Oracle Corporation', 'ORCL', 'NYSE'),
  eq('Cisco Systems Inc.', 'CSCO', 'NASDAQ'),
  eq('Broadcom Inc.', 'AVGO', 'NASDAQ'),
  eq('QUALCOMM Incorporated', 'QCOM', 'NASDAQ'),
  eq('Texas Instruments Incorporated', 'TXN', 'NASDAQ'),
  eq('Micron Technology Inc.', 'MU', 'NASDAQ'),
  eq('Applied Materials Inc.', 'AMAT', 'NASDAQ'),
  eq('Marvell Technology Inc.', 'MRVL', 'NASDAQ'),
  eq('Analog Devices Inc.', 'ADI', 'NASDAQ'),
  eq('Lam Research Corporation', 'LRCX', 'NASDAQ'),
  eq('KLA Corporation', 'KLAC', 'NASDAQ'),
  eq('Arm Holdings plc ADR', 'ARM', 'NASDAQ'),
  eq('Super Micro Computer Inc.', 'SMCI', 'NASDAQ'),
  eq('International Business Machines', 'IBM', 'NYSE'),
  eq('UnitedHealth Group Incorporated', 'UNH', 'NYSE'),
  eq('Eli Lilly and Company', 'LLY', 'NYSE'),
  eq('Merck & Co. Inc.', 'MRK', 'NYSE'),
  eq('Pfizer Inc.', 'PFE', 'NYSE'),
  eq('AbbVie Inc.', 'ABBV', 'NYSE'),
  eq('Bristol-Myers Squibb Company', 'BMY', 'NYSE'),
  eq('Amgen Inc.', 'AMGN', 'NASDAQ'),
  eq('Gilead Sciences Inc.', 'GILD', 'NASDAQ'),
  eq('Thermo Fisher Scientific Inc.', 'TMO', 'NYSE'),
  eq('Abbott Laboratories', 'ABT', 'NYSE'),
  eq('Danaher Corporation', 'DHR', 'NYSE'),
  eq('Intuitive Surgical Inc.', 'ISRG', 'NASDAQ'),
  eq('Bank of America Corporation', 'BAC', 'NYSE'),
  eq('Wells Fargo & Company', 'WFC', 'NYSE'),
  eq('The Goldman Sachs Group Inc.', 'GS', 'NYSE'),
  eq('Morgan Stanley', 'MS', 'NYSE'),
  eq('Citigroup Inc.', 'C', 'NYSE'),
  eq('American Express Company', 'AXP', 'NYSE'),
  eq('BlackRock Inc.', 'BLK', 'NYSE'),
  eq('The Charles Schwab Corporation', 'SCHW', 'NYSE'),
  eq('S&P Global Inc.', 'SPGI', 'NYSE'),
  eq("Moody's Corporation", 'MCO', 'NYSE'),
  eq('The Walt Disney Company', 'DIS', 'NYSE'),
  eq('NIKE Inc.', 'NKE', 'NYSE'),
  eq("McDonald's Corporation", 'MCD', 'NYSE'),
  eq('Starbucks Corporation', 'SBUX', 'NASDAQ'),
  eq('AT&T Inc.', 'T', 'NYSE'),
  eq('Verizon Communications Inc.', 'VZ', 'NYSE'),
  eq('T-Mobile US Inc.', 'TMUS', 'NASDAQ'),
  eq('General Electric Company', 'GE', 'NYSE'),
  eq('Caterpillar Inc.', 'CAT', 'NYSE'),
  eq('The Boeing Company', 'BA', 'NYSE'),
  eq('3M Company', 'MMM', 'NYSE'),
  eq('Honeywell International Inc.', 'HON', 'NASDAQ'),
  eq('United Parcel Service Inc.', 'UPS', 'NYSE'),
  eq('FedEx Corporation', 'FDX', 'NYSE'),
  eq('RTX Corporation', 'RTX', 'NYSE'),
  eq('Lockheed Martin Corporation', 'LMT', 'NYSE'),
  eq('Deere & Company', 'DE', 'NYSE'),
  eq('PayPal Holdings Inc.', 'PYPL', 'NASDAQ'),
  eq('Shopify Inc.', 'SHOP', 'NYSE'),
  eq('Uber Technologies Inc.', 'UBER', 'NYSE'),
  eq('Airbnb Inc.', 'ABNB', 'NASDAQ'),
  eq('Coinbase Global Inc.', 'COIN', 'NASDAQ'),
  eq('Palantir Technologies Inc.', 'PLTR', 'NASDAQ'),
  eq('Snowflake Inc.', 'SNOW', 'NYSE'),
  eq('Spotify Technology S.A.', 'SPOT', 'NYSE'),
  eq('Palo Alto Networks Inc.', 'PANW', 'NASDAQ'),
  eq('ServiceNow Inc.', 'NOW', 'NYSE'),
  eq('Intuit Inc.', 'INTU', 'NASDAQ'),
  eq('Booking Holdings Inc.', 'BKNG', 'NASDAQ'),
  eq('Marriott International Inc.', 'MAR', 'NASDAQ'),
  eq('Linde plc', 'LIN', 'NASDAQ'),
  eq('NextEra Energy Inc.', 'NEE', 'NYSE'),
  eq("Lowe's Companies Inc.", 'LOW', 'NYSE'),
  eq('Target Corporation', 'TGT', 'NYSE'),
  eq('The TJX Companies Inc.', 'TJX', 'NYSE'),
  eq('General Motors Company', 'GM', 'NYSE'),
  eq('Ford Motor Company', 'F', 'NYSE'),
  eq('Rivian Automotive Inc.', 'RIVN', 'NASDAQ'),
  eq('Taiwan Semiconductor ADR', 'TSM', 'NYSE'),
  eq('ASML Holding N.V. ADR', 'ASML', 'NASDAQ'),
  eq('Alibaba Group Holding ADR', 'BABA', 'NYSE'),
  eq('JD.com Inc. ADR', 'JD', 'NASDAQ'),
  eq('PDD Holdings Inc. ADR', 'PDD', 'NASDAQ'),
  eq('NIO Inc. ADR', 'NIO', 'NYSE'),
  eq('Sony Group Corporation ADR', 'SONY', 'NYSE'),
  eq('Toyota Motor Corporation ADR', 'TM', 'NYSE'),
];

export const US_ETFS: SecurityEntry[] = [
  etf('SPDR S&P 500 ETF Trust', 'SPY', 'NYSEARCA'),
  etf('Vanguard S&P 500 ETF', 'VOO', 'NYSEARCA'),
  etf('iShares Core S&P 500 ETF', 'IVV', 'NYSEARCA'),
  etf('Vanguard Total Stock Market ETF', 'VTI', 'NYSEARCA'),
  etf('Invesco QQQ Trust', 'QQQ', 'NASDAQ'),
  etf('SPDR Dow Jones Industrial Average ETF', 'DIA', 'NYSEARCA'),
  etf('iShares Russell 2000 ETF', 'IWM', 'NYSEARCA'),
  etf('Vanguard FTSE Developed Markets ETF', 'VEA', 'NYSEARCA'),
  etf('Vanguard FTSE Emerging Markets ETF', 'VWO', 'NYSEARCA'),
  etf('iShares MSCI EAFE ETF', 'EFA', 'NYSEARCA'),
  etf('iShares MSCI Emerging Markets ETF', 'EEM', 'NYSEARCA'),
  etf('iShares Core U.S. Aggregate Bond ETF', 'AGG', 'NYSEARCA'),
  etf('Vanguard Total Bond Market ETF', 'BND', 'NASDAQ'),
  etf('iShares 20+ Year Treasury Bond ETF', 'TLT', 'NASDAQ'),
  etf('iShares iBoxx $ Inv Grade Corporate Bond ETF', 'LQD', 'NYSEARCA'),
  etf('iShares iBoxx $ High Yield Corporate Bond ETF', 'HYG', 'NYSEARCA'),
  etf('SPDR Gold Shares', 'GLD', 'NYSEARCA'),
  etf('iShares Silver Trust', 'SLV', 'NYSEARCA'),
  etf('VanEck Gold Miners ETF', 'GDX', 'NYSEARCA'),
  etf('Technology Select Sector SPDR Fund', 'XLK', 'NYSEARCA'),
  etf('Financial Select Sector SPDR Fund', 'XLF', 'NYSEARCA'),
  etf('Energy Select Sector SPDR Fund', 'XLE', 'NYSEARCA'),
  etf('Health Care Select Sector SPDR Fund', 'XLV', 'NYSEARCA'),
  etf('Consumer Discretionary Select SPDR Fund', 'XLY', 'NYSEARCA'),
  etf('Consumer Staples Select Sector SPDR Fund', 'XLP', 'NYSEARCA'),
  etf('Industrial Select Sector SPDR Fund', 'XLI', 'NYSEARCA'),
  etf('Utilities Select Sector SPDR Fund', 'XLU', 'NYSEARCA'),
  etf('Vanguard Real Estate ETF', 'VNQ', 'NYSEARCA'),
  etf('Schwab U.S. Dividend Equity ETF', 'SCHD', 'NYSEARCA'),
  etf('Vanguard Dividend Appreciation ETF', 'VIG', 'NYSEARCA'),
  etf('Vanguard High Dividend Yield ETF', 'VYM', 'NYSEARCA'),
  etf('JPMorgan Equity Premium Income ETF', 'JEPI', 'NYSEARCA'),
  etf('ARK Innovation ETF', 'ARKK', 'NYSEARCA'),
  etf('VanEck Semiconductor ETF', 'SMH', 'NASDAQ'),
  etf('iShares Semiconductor ETF', 'SOXX', 'NASDAQ'),
  etf('iShares Bitcoin Trust ETF', 'IBIT', 'NASDAQ'),
];
